### ISSUE TITLE
Formatting broken when using ansi colours

### ISSUE THREAD

**Issue by maximih** [BurntSushi/tabwriter#1]
I am trying to combine `tabwriter` and `ansi_term` crate to format some text output but `tabwriter` doesn't seem to handle the ANSI escape code and the formatting fails. I have no idea how this works in detail so I cannot probably provide a fix.

The code:

```rust
extern crate tabwriter;
extern crate ansi_term;
use ansi_term::Colour::Red;
use tabwriter::TabWriter;
use std::io::Write;

fn tabify(mut tw: TabWriter<Vec<u8>>, s: &str) -> String {
    write!(&mut tw, "{}", s).unwrap();
    tw.flush().unwrap();
    String::from_utf8(tw.unwrap()).unwrap()
}

fn main() {
	let output = format!("Title1\tTitle2\tTitle3\n{}\t{}\t{}",
		                       Red.paint("value1"), Red.paint("value2"), Red.paint("value3"));

    let tw = TabWriter::new(Vec::<u8>::new());
    println!("{}", tabify(tw, &output[..]));
}
```

The output when running the code above:

```bash
Title1         Title2         Title3
value1  value2  value3
```

**Comment by BurntSushi** [comment]
I'm not sure how this could be reasonably expected to work. `tabwriter` doesn't know or care about ANSI escape sequences, so it treats each character in the escape sequence as just another character. This probably results in `tabwriter` thinking that the output is much wider than it is actually displayed in the terminal. Indeed, that is probably why you're observing the plain "Title" headings so far apart while the values are closer together.

I don't have any good ideas for a work-around.

**Comment by maximih** [comment]
I guess we can create a list/set with all the ANSI escape codes and remove them from the original string before`tabwriter` is calculating the length of each word between tabs. I did no check the code but I guess this can be done. I can read a bit about the ANSI escape codes and try to create a patch.

**Comment by BurntSushi** [comment]
That seems possible.

**Comment by maximih** [comment]
Fixed in https://github.com/BurntSushi/tabwriter/commit/df39660e299174e96a68a53ce49ee04b00ceb767

**Comment by vitiral** [comment]
is this still supposed to work? I am getting wildly different tab lengths when adding color in v1.0.3

Thanks

**Comment by BurntSushi** [comment]
@vitiral Please file a new issue with a reproducible example.

**Comment by vitiral** [comment]
will do, thanks

**Comment by vitiral** [comment]
I'm an idiot, I missed the `ani_formatting` feature. Now it works great!
