### ISSUE TITLE
padding(0) gives one space of padding

### ISSUE THREAD

**Issue by BartMassey** [BurntSushi/tabwriter#26]
It looks like the minimum padding is one space, with `padding(n)` giving `n+1` spaces of padding? The documentation says otherwise, so I'm a little confused.

```rust
use std::io::{Write, stdout};

use tabwriter::TabWriter;

fn main() {
    let mut tw = TabWriter::new(stdout()).padding(0);
    writeln!(tw, "{}\t{}", 1, 2).unwrap();
    tw.flush().unwrap();
}
```

Outputs "1 2"

**Comment by BurntSushi** [comment]
I believe this is correct behavior. There are two points here: some weaselly wording in the docs and the presence of `minwidth`. First, the docs, emphasis mine:

> Set the padding between columns. All columns will be separated by **at least** the number of spaces indicated by padding. If padding is zero, then columns **may** run up against each other without any separation.

So _technically_, with that alone, what you're seeing is allowed.

But the other thing here is [`TabWriter::minwidth`](https://docs.rs/tabwriter/1.1.0/tabwriter/struct.TabWriter.html#method.minwidth), which is set to `2` by default. If you set this to `1` in your example, then the padding between your columns will disappear.

**Comment by BartMassey** [comment]
Thanks much for the clarification!
