### ISSUE TITLE
move binary to src

### ISSUE THREAD

**Issue by vks** [BurntSushi/tabwriter#3]
I don't know what the motivation for having the binary in its own directory with its own `Cargo.toml` is, but I think it makes more sense to just move `main.rs` to `src` and delete the other files.

**Comment by vks** [comment]
Is it possible to specify dependencies for the binary only?

**Comment by BurntSushi** [comment]
Can you explain a bit more why you think that is? `tabwriter-bin` has a dependency on both `docopt.rs` and `rustc-serialize`. Neither of these dependencies are necessary for this library's core functionality, so I see little reason to impose them on consumers.

**Comment by BurntSushi** [comment]
> Is it possible to specify dependencies for the binary only?

@vks No.

**Comment by vks** [comment]
Well, then I see why you need two `Cargo.toml`s, that is unfortunate.

(BTW, `tabwriter-bin` needs a `cargo update` to build.)

**Comment by vks** [comment]
See https://github.com/rust-lang/cargo/issues/1982 for implementing binary-only dependencies in Cargo.

**Comment by BurntSushi** [comment]
I don't feel any compelling urge to do this. If `cargo` grows this in the future at some point, we can revisit.
