### ISSUE TITLE
Possible to disable alignment for certain lines? 

### ISSUE THREAD

**Issue by sefeng211** [BurntSushi/tabwriter#31]
Hi,

I have a usecase that I want to add a line in between of some other lines, and I don't want the length of this line to be considered during alignment. Is it possible?

Thanks!

**Comment by BurntSushi** [comment]
I think the docs show what's possible. You could write a line without tabs. Or an empty line. Calling `flush` before and immediately after writing your line may work too, but I'm not sure.

**Comment by sefeng211** [comment]
If I write a line without tabs, the rest of the lines are not aligned together with previous lines.

**Comment by BurntSushi** [comment]
Yeah, that's an intentional feature. See the examples in the docs. This crate has a pretty narrow focus on elastic tabstops with some limited customizations. If you need something more elaborate, you'll need to find another way.
