### ISSUE TITLE
approaching 1.0

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/tabwriter#7]
This crate has a small API and is not widely used. With no obvious uptick in usage on the horizon, I suggest we cut a 1.0 release.

**Comment by gkoz** [comment]
It seems a more idiomatic name for `unwrap` might be `into_inner`. Also is there value in it not flushing automatically?

**Comment by BurntSushi** [comment]
`into_inner` is probably better, yeah.

I'm not sure what the use case is for it to not flush automatically. The idea with flushing automatically is to at least try and not buffer the entire contents into memory at once. In fact, this is a large part of the complexity of this library.

**Comment by gkoz** [comment]
Sorry for not being clear enough, I mean the `unwrap` docs say it won't flush (a possible footgun) but is there a good reason for that?

**Comment by BurntSushi** [comment]
Oooo! Right. Given that the [analogous method on BufWriter flushes the buffer](https://doc.rust-lang.org/std/io/struct.BufWriter.html#method.into_inner), I think `tabwriter` should probably do the same. Thanks so much for bringing this up, I probably would have completely missed it otherwise!
