### ISSUE TITLE
Allow Center and Right Alignment of Texts

### ISSUE THREAD

**Issue by CryZe** [BurntSushi/tabwriter#8]
This would be really useful for Headers and Numbers. Looks like it's unstable at the moment however: https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.align

**Comment by BurntSushi** [comment]
If we were to implement that here, we wouldn't use `fmt::Formatter` anyway.

The [Go package that inspired this library](https://golang.org/pkg/text/tabwriter/) does support right alignment.

**Comment by vincentdephily** [comment]
Note that the go library sets alignment (and padding and minwidth) globally, but it would be very useful (especially for alignment) to set it per-field, perhaps at `flush()` time.

I'm outputing mixed-alignment fields and do the right-alignments in the format string, but then I have to plan for the longest strings myself.

**Comment by BurntSushi** [comment]
@vincentdephily That's a completely different feature request than what this issue is asking for. Normally I'd request that you just open it as a separate ticket, but it's well beyond the scope of this crate. If you want it, I'd encourage you to build a new crate.
